### PR TITLE
Backward-compatible changes pre-contactmatrix integration

### PR DESCRIPTION
**Pull request by Bisaloo**
The changes in this PR should be (mostly) backward-compatible. A follow up PR will propose breaking changes integrating socialmixr with contactmatrix.

### CODE REVIEW

**Comment by sbfnk** [comment]
Just looking at the conflicts now.

**Comment by sbfnk** [comment]
Snapshot test failure is due to different print methods between `xtabs` and `matrix`

**Comment by sbfnk** [comment]
@Bisaloo can we merge?

**Comment by Bisaloo** [comment]
Yes, sound good. Further changes can be added in follow up PRs

**Pull request merged**
