### PR TITLE
Add tolerance to equality tests

### LINKED ISSUE #99: CRAN checks failing
We're currently seeing an error on a couple of platforms
https://cran.r-project.org/web/checks/check_results_socialmixr.html
and have been given until 3 November to fix it.

From a quick glance it's not obvious to me what the cause of the error is.

### PR DESCRIPTION
**Pull request by Bisaloo**
Hopefully fixes #99 

I don't have access to a noLD platform right now but I can give r-hub a spin

### CODE REVIEW

**Comment by sbfnk** [comment]
Not seeing any arm64 (is that the same as noLD?) platforms in https://github.com/r-hub/rhub2/blob/v1/actions/rhub-setup/platforms.json 

That said I agree that this should fix things so will send to CRAN.

**Review by sbfnk — APPROVED** [review]

**Comment by Bisaloo** [comment]
> Not seeing any arm64 (is that the same as noLD?) platforms in [r-hub/rhub2@v1/actions/rhub-setup/platforms.json](https://github.com/r-hub/rhub2/blob/v1/actions/rhub-setup/platforms.json?rgh-link-date=2023-10-25T07%3A28%3A32Z)

No, it's not the same but the errors (more errors actually) were also visible on the CRAN noLD platform so it's probably a good test case.

**Comment by sbfnk** [comment]
> No, it's not the same but the errors (more errors actually) were also visible on the CRAN noLD platform so it's probably a good test case.

Ah yes I only saw this now and agree. Not having much joy with rhub due to missing pandoc-citeproc but can just submit as is.

**Comment by sbfnk** [comment]
All good when sent manually to rhub with nold:
https://builder.r-hub.io/status/socialmixr_0.3.1.tar.gz-174a455351174d3ab45ce8270da09444

Thanks again!

**Comment by sbfnk** [comment]
This did the trick - all checks passing.

**Pull request merged**
