### PR TITLE
add package author

### PR DESCRIPTION
**Pull request by sbfnk**
@lwillem are you OK with this? Would you like me to add an email address, middle name etc.

### CODE REVIEW

**Comment by lwillem** [comment]
Great! Thanks! No middle name or email required. Would it be possible to include Niel Hens as well? We worked together on the code I added.

**Comment by sbfnk** [comment]
> Great! Thanks! No middle name or email required. Would it be possible to include Niel Hens as well? We worked together on the code I added.

Of course! Either create a PR to this one, or just do it all in your [big PR](https://github.com/epiforecasts/socialmixr/pull/28).

**Comment by sbfnk** [comment]
I've added you as an author, @lwillem - for Niel, should this be an author or contributor role? From https://r-pkgs.org/description.html:

- aut: authors, those who have made significant contributions to the package.
- ctb: contributors, those who have made smaller contributions, like patches.

**Comment by lwillem** [comment]
ctb seems OK, like you added. thanks!

**Pull request merged**
