### PR TITLE
Hugo's review, take 2

### PR DESCRIPTION
**Pull request by Bisaloo**
Supersedes #31

### CODE REVIEW

**Comment by sbfnk** [comment]
Thanks!

- It seems like now is a good time to agree on a style - do we perhaps want some stricter style guidelines? I'm not hugely familiar with `styler` vs. `formatR` vs. `lintr` but if we're updating style then as an example I think it would be good to e.g. have an 80 character line width limit (which we currently break in many places).
- Do we also need a GH action for codecov?
- With the switch to GH actions we should update the badge(s) in the README

**Comment by Bisaloo** [comment]
It seems like automated tools don't support fixing lines longer than 80 characters for now. lintr can print warning for this but I find it more annoying than anything since it badgers you but doesn't actually help you fixing it.

I would vote to merge this first round now so I can continue with more in-depth changes (now that I'll have a clear pkgdown website) and we can revisit styling later, once tools have evolved.

**Comment by sbfnk** [comment]
Sounds good to me - fixing long lines is quite a satisfying manual activity while on a zoom call that only requires half attention.

**Comment by sbfnk** [comment]
Whilst we're on general things, any preference for merge commit vs. squash merge vs rebase merge? I tend to squash when the commit history is untidy but e.g. in this PR I'd think a merge commit makes more sense as the commit messages are explicit and potentially useful in the future.

**Comment by Bisaloo** [comment]
I like using squash and merge for untidy history but usually I use rebase & merge otherwise. I find it easier to read the history since:

1. Commits are ordered correctly. All the commits from the PR are together at the current HEAD, not at seemingly random locations. This is especially true for PR that tend to wait a long time before getting merged. Maybe it's my fault for not using a GUI which shows branches over time but at least, it's how it is in GitHub web interface.
2. Your history is not polluted with merge commits

From what I understand, Linus begs to differ and prefers merge commits though. I should take some time to investigate why at some point :thinking:

**Comment by sbfnk** [comment]
My first time using a rebase merge - looks snazzy with the two portraits next to each commit ;-)

**Pull request merged**
